python_library(
  name='fabfile_support',
  dependencies=[
    'src/python/uc/fab/foobar',
  ],
)

python_binary(
  name='fab_bin',
  dependencies=[
    ':fabfile_support',
  ],
  source='__init__.py',
)
